image: synedra/dockercodetour

tasks:
  - name: tiktok
    command: |
      cp -r /workspace/appsembler-tiktok/root/config/workspace/ /workspace
      cp -r /workspace/appsembler-tiktok/root/config/data/User/settings.json /workspace/appsembler-tiktok/.vscode/settings.json

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore 
  - port: 8443
    onOpen: ignore
