image: 
  file: Dockerfile

vscode:
  extensions:
    - vsls-contrib.codetour
    - auchenberg.vscode-browser-preview
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/gabrielgrinberg/vsextensions/auto-run-command/1.6.0/vspackage
  
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore 
  - port: 8443
    onOpen: ignore
