image: 
  file: Dockerfile

vscode:
  extensions:
    - vsls-contrib.codetour-0.0.58
    - gabrielgrinberg.auto-run-command-1.5.0
    - auchenberg.vscode-browser-preview-0.7.1
  
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore 
  - port: 8443
    onOpen: ignore
