image: synedra/dockercodetour

tasks:
  - name: tiktok
    command: |
      cd /workspace
      git clone https://github.com/synedra/appdev-week2-tiktok tik-tok-full
      gp preview /workspace/tik-tok-full/README.md

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false
ports:
  - port: 8888
    onOpen: open-preview
  - port: 3000
    onOpen: ignore 
